name:                type-match
version:             0.1.0.0
github:              "owestphal/type-match"
license:             BSD3
author:              "Oliver Westphal"
maintainer:          "owestphal-haskell <a> posteo <dot> de"
copyright:           "2022 Oliver Westphal"

extra-source-files:
- README.md

synopsis:            Pattern matching on types
category:            Pattern

description:         Please see the README on GitHub at <https://github.com/owestphal/type-match#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
